version: '3.5'
networks:
  backend:
    driver: bridge
    attachable: true
services:
  mysqlsh:
    stdin_open: true
    image: mysql-shell:latest
    environment:
      - SERVICE_IGNORE=true
    tty: true
    networks:
      - backend
    command: mysqlsh --py
